<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\CompetitiveExam;
use App\Models\EducationSector;
use App\Models\EducationStream;

class CompetitiveExamSeeder extends Seeder
{
    public function run()
    {
        $sectors = EducationSector::all()->keyBy('key');
        $streams = EducationStream::all()->keyBy('key');

        $exams = [
            // Engineering Exams (After 12th)
            [
                'sector_id' => $sectors['engineering']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'jee-main',
                'name_hindi' => 'JEE Main (Joint Entrance Examination)',
                'name_english' => 'JEE Main (Joint Entrance Examination)',
                'sector' => 'engineering',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['12वीं PCM पास', 'Age limit: 18-25 years', 'Maximum 2 attempts'],
                'eligibility_english' => ['12th PCM pass', 'Age limit: 18-25 years', 'Maximum 2 attempts'],
                'exam_pattern' => 'MCQ',
                'frequency' => 'twice a year',
                'subjects_hindi' => ['भौतिकी', 'रसायन', 'गणित'],
                'subjects_english' => ['Physics', 'Chemistry', 'Mathematics'],
                'preparation_tips_hindi' => 'नियमित अभ्यास, पिछले वर्ष के प्रश्न पत्र, ऑनलाइन टेस्ट सीरीज, NCERT की किताबों का गहन अध्ययन',
                'preparation_tips_english' => 'Regular practice, previous year papers, online test series, thorough study of NCERT books',
                'official_website' => 'https://jeemain.nta.nic.in',
                'registration_period' => 'December-January, March-April',
                'exam_months' => 'January, April',
                'sort_order' => 1,
            ],
            [
                'sector_id' => $sectors['engineering']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'jee-advanced',
                'name_hindi' => 'JEE Advanced',
                'name_english' => 'JEE Advanced',
                'sector' => 'engineering',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['JEE Main में Top 2.5 लाख rank holders', '12वीं में कम से कम 75% अंक'],
                'eligibility_english' => ['Top 2.5 lakh rank holders in JEE Main', 'Minimum 75% marks in 12th'],
                'exam_pattern' => 'MCQ + Numerical',
                'frequency' => 'once a year',
                'subjects_hindi' => ['भौतिकी', 'रसायन', 'गणित'],
                'subjects_english' => ['Physics', 'Chemistry', 'Mathematics'],
                'preparation_tips_hindi' => 'गहरी समझ, उच्च स्तरीय समस्याएं, coaching की सलाह, पिछले वर्ष के प्रश्न पत्र',
                'preparation_tips_english' => 'Deep understanding, high-level problems, coaching advice, previous year papers',
                'official_website' => 'https://jeeadv.ac.in',
                'registration_period' => 'May',
                'exam_months' => 'May',
                'sort_order' => 2,
            ],
            [
                'sector_id' => $sectors['engineering']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'bitsat',
                'name_hindi' => 'BITSAT (Birla Institute of Technology and Science Admission Test)',
                'name_english' => 'BITSAT (Birla Institute of Technology and Science Admission Test)',
                'sector' => 'engineering',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['12वीं PCM में कम से कम 75% अंक', 'अच्छी अंग्रेजी प्रवीणता'],
                'eligibility_english' => ['Minimum 75% marks in 12th PCM', 'Good English proficiency'],
                'exam_pattern' => 'MCQ',
                'frequency' => 'once a year',
                'subjects_hindi' => ['भौतिकी', 'रसायन', 'गणित', 'अंग्रेजी', 'लॉजिकल रीजनिंग'],
                'subjects_english' => ['Physics', 'Chemistry', 'Mathematics', 'English', 'Logical Reasoning'],
                'preparation_tips_hindi' => 'अंग्रेजी पर विशेष ध्यान, BITSAT पैटर्न अभ्यास, समय प्रबंधन',
                'preparation_tips_english' => 'Special focus on English, BITSAT pattern practice, time management',
                'official_website' => 'https://bitsadmission.com',
                'registration_period' => 'February-March',
                'exam_months' => 'May-June',
                'sort_order' => 3,
            ],

            // Medical Exams (After 12th)
            [
                'sector_id' => $sectors['medicine']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'neet-ug',
                'name_hindi' => 'NEET-UG (National Eligibility cum Entrance Test)',
                'name_english' => 'NEET-UG (National Eligibility cum Entrance Test)',
                'sector' => 'medicine',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['12वीं PCB में कम से कम 50% अंक (General), 40% (SC/ST/OBC)', 'Age: 17-25 years'],
                'eligibility_english' => ['Minimum 50% marks in 12th PCB (General), 40% (SC/ST/OBC)', 'Age: 17-25 years'],
                'exam_pattern' => 'MCQ',
                'frequency' => 'once a year',
                'subjects_hindi' => ['भौतिकी', 'रसायन', 'जीव विज्ञान'],
                'subjects_english' => ['Physics', 'Chemistry', 'Biology'],
                'preparation_tips_hindi' => 'NCERT Biology पर गहरा ध्यान, Biology के diagrams याद करना, Physics और Chemistry में numerical practice',
                'preparation_tips_english' => 'Deep focus on NCERT Biology, memorize Biology diagrams, practice numerical in Physics and Chemistry',
                'official_website' => 'https://neet.nta.nic.in',
                'registration_period' => 'February-March',
                'exam_months' => 'May',
                'sort_order' => 4,
            ],

            // Commerce Exams (After 12th)
            [
                'sector_id' => $sectors['commerce']->id,
                'stream_id' => $streams['commerce']->id,
                'key' => 'cuet',
                'name_hindi' => 'CUET (Common University Entrance Test)',
                'name_english' => 'CUET (Common University Entrance Test)',
                'sector' => 'commerce',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['12वीं पास (किसी भी स्ट्रीम)', 'Central Universities में admission के लिए'],
                'eligibility_english' => ['12th pass (any stream)', 'For admission in Central Universities'],
                'exam_pattern' => 'MCQ',
                'frequency' => 'once a year',
                'subjects_hindi' => ['अंग्रेजी', 'गणित/अर्थशास्त्र', 'अपना chosen subject'],
                'subjects_english' => ['English', 'Mathematics/Economics', 'Your chosen subject'],
                'preparation_tips_hindi' => 'अंग्रेजी की तैयारी, current affairs, chosen subject में depth',
                'preparation_tips_english' => 'English preparation, current affairs, depth in chosen subject',
                'official_website' => 'https://cuet.samarth.ac.in',
                'registration_period' => 'March-April',
                'exam_months' => 'May-June',
                'sort_order' => 5,
            ],

            // Government Job Exams (After Graduation)
            [
                'sector_id' => $sectors['government']->id,
                'stream_id' => null,
                'key' => 'ssc-cgl',
                'name_hindi' => 'SSC CGL (Staff Selection Commission Combined Graduate Level)',
                'name_english' => 'SSC CGL (Staff Selection Commission Combined Graduate Level)',
                'sector' => 'government',
                'applicable_for' => 'govt_job',
                'eligibility_class' => 'graduation',
                'eligibility_hindi' => ['किसी भी स्ट्रीम में स्नातक', 'Age: 18-32 years'],
                'eligibility_english' => ['Graduation in any stream', 'Age: 18-32 years'],
                'exam_pattern' => 'MCQ + Descriptive',
                'frequency' => 'once a year',
                'subjects_hindi' => ['General Intelligence', 'General Awareness', 'Quantitative Aptitude', 'English'],
                'subjects_english' => ['General Intelligence', 'General Awareness', 'Quantitative Aptitude', 'English'],
                'preparation_tips_hindi' => 'Current affairs, English की तैयारी, quantitative aptitude practice, previous year papers',
                'preparation_tips_english' => 'Current affairs, English preparation, quantitative aptitude practice, previous year papers',
                'official_website' => 'https://ssc.nic.in',
                'registration_period' => 'Throughout the year',
                'exam_months' => 'August-December',
                'sort_order' => 6,
            ],
            [
                'sector_id' => $sectors['government']->id,
                'stream_id' => null,
                'key' => 'upsc-cse',
                'name_hindi' => 'UPSC CSE (Civil Services Examination)',
                'name_english' => 'UPSC CSE (Civil Services Examination)',
                'sector' => 'government',
                'applicable_for' => 'govt_job',
                'eligibility_class' => 'graduation',
                'eligibility_hindi' => ['किसी भी स्ट्रीम में स्नातक', 'Age: 21-32 years'],
                'eligibility_english' => ['Graduation in any stream', 'Age: 21-32 years'],
                'exam_pattern' => 'Preliminary (MCQ) + Mains (Descriptive) + Interview',
                'frequency' => 'once a year',
                'subjects_hindi' => ['History', 'Geography', 'Polity', 'Economics', 'Environment', 'Science'],
                'subjects_english' => ['History', 'Geography', 'Polity', 'Economics', 'Environment', 'Science'],
                'preparation_tips_hindi' => 'NCERT books, newspaper reading, answer writing practice, current affairs, extensive reading',
                'preparation_tips_english' => 'NCERT books, newspaper reading, answer writing practice, current affairs, extensive reading',
                'official_website' => 'https://upsc.gov.in',
                'registration_period' => 'February-March',
                'exam_months' => 'June (Prelims), September (Mains)',
                'sort_order' => 7,
            ],

            // Defence Exams (After 12th)
            [
                'sector_id' => $sectors['defence']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'nda',
                'name_hindi' => 'NDA (National Defence Academy)',
                'name_english' => 'NDA (National Defence Academy)',
                'sector' => 'defence',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['12वीं पास (Science stream recommended)', 'Age: 16.5-19.5 years', 'Unmarried male candidates'],
                'eligibility_english' => ['12th pass (Science stream recommended)', 'Age: 16.5-19.5 years', 'Unmarried male candidates'],
                'exam_pattern' => 'MCQ + Descriptive',
                'frequency' => 'twice a year',
                'subjects_hindi' => ['Mathematics', 'General Ability Test (English, History, Geography, Physics, Chemistry)'],
                'subjects_english' => ['Mathematics', 'General Ability Test (English, History, Geography, Physics, Chemistry)'],
                'preparation_tips_hindi' => 'Physical fitness, current affairs, English improvement, basic science concepts',
                'preparation_tips_english' => 'Physical fitness, current affairs, English improvement, basic science concepts',
                'official_website' => 'https://upsc.gov.in',
                'registration_period' => 'January, July',
                'exam_months' => 'April, September',
                'sort_order' => 8,
            ],

            // Law Exams (After Graduation)
            [
                'sector_id' => $sectors['law']->id,
                'stream_id' => null,
                'key' => 'clat',
                'name_hindi' => 'CLAT (Common Law Admission Test)',
                'name_english' => 'CLAT (Common Law Admission Test)',
                'sector' => 'law',
                'applicable_for' => 'degree',
                'eligibility_class' => '12',
                'eligibility_hindi' => ['12वीं पास (किसी भी स्ट्रीम)', 'Minimum 45% marks', 'Age: Below 20 years'],
                'eligibility_english' => ['12th pass (any stream)', 'Minimum 45% marks', 'Age: Below 20 years'],
                'exam_pattern' => 'MCQ',
                'frequency' => 'once a year',
                'subjects_hindi' => ['English', 'Current Affairs', 'Legal Reasoning', 'Logical Reasoning', 'Mathematics'],
                'subjects_english' => ['English', ' Affairs', 'Legal Reasoning', 'Logical Reasoning', 'Mathematics'],
                'preparation_tips_hindi' => 'Legal awareness, current affairs, logical reasoning practice, English comprehension',
                'preparation_tips_english' => 'Legal awareness, current affairs, logical reasoning practice, English comprehension',
                'official_website' => 'https://consortiumofnlus.ac.in/clat',
                'registration_period' => 'December-January',
                'exam_months' => 'May',
                'sort_order' => 9,
            ],

            // Banking Exams (After Graduation)
            [
                'sector_id' => $sectors['government']->id,
                'stream_id' => null,
                'key' => 'ibps-po',
                'name_hindi' => 'IBPS PO (Institute of Banking Personnel Selection - Probationary Officer)',
                'name_english' => 'IBPS PO (Institute of Banking Personnel Selection - Probationary Officer)',
                'sector' => 'government',
                'applicable_for' => 'govt_job',
                'eligibility_class' => 'graduation',
                'eligibility_hindi' => ['किसी भी स्ट्रीम में स्नातक', 'Age: 20-30 years'],
                'eligibility_english' => ['Graduation in any stream', 'Age: 20-30 years'],
                'exam_pattern' => 'Preliminary (MCQ) + Mains (MCQ + Descriptive)',
                'frequency' => 'once a year',
                'subjects_hindi' => ['Reasoning', 'Quantitative Aptitude', 'English', 'General Awareness', 'Computer Knowledge'],
                'subjects_english' => ['Reasoning', 'Quantitative Aptitude', 'English', 'General Awareness', 'Computer Knowledge'],
                'preparation_tips_hindi' => 'Banking awareness, quantitative aptitude, reasoning practice, English improvement',
                'preparation_tips_english' => 'Banking awareness, quantitative aptitude, reasoning practice, English improvement',
                'official_website' => 'https://ibps.in',
                'registration_period' => 'August-September',
                'exam_months' => 'November-December',
                'sort_order' => 10,
            ],

            // Railway Exams (After 12th/Graduation)
            [
                'sector_id' => $sectors['government']->id,
                'stream_id' => null,
                'key' => 'rrb-ntpc',
                'name_hindi' => 'RRB NTPC (Railway Recruitment Board - Non-Technical Popular Categories)',
                'name_english' => 'RRB NTPC (Railway Recruitment Board - Non-Technical Popular Categories)',
                'sector' => 'government',
                'applicable_for' => 'govt_job',
                'eligibility_class' => 'graduation',
                'eligibility_hindi' => ['किसी भी स्ट्रीम में स्नातक', 'Age: 18-33 years'],
                'eligibility_english' => ['Graduation in any stream', 'Age: 18-33 years'],
                'exam_pattern' => 'MCQ',
                'frequency' => 'as per requirement',
                'subjects_hindi' => ['General Awareness', 'Mathematics', 'General Intelligence and Reasoning'],
                'subjects_english' => ['General Awareness', 'Mathematics', 'General Intelligence and Reasoning'],
                'preparation_tips_hindi' => 'Current affairs, mathematics practice, reasoning, railway knowledge',
                'preparation_tips_english' => 'Current affairs, mathematics practice, reasoning, railway knowledge',
                'official_website' => 'https://www.rrbcdg.gov.in',
                'registration_period' => 'Throughout the year',
                'exam_months' => 'Varies',
                'sort_order' => 11,
            ],
        ];

        foreach ($exams as $exam) {
            CompetitiveExam::updateOrCreate(
                ['key' => $exam['key']],
                $exam
            );
        }
    }
}
