<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Course;
use App\Models\EducationSector;
use App\Models\EducationStream;

class CourseSeeder extends Seeder
{
    public function run()
    {
        $sectors = EducationSector::all()->keyBy('key');
        $streams = EducationStream::all()->keyBy('key');

        $courses = [
            // Engineering Courses
            [
                'sector_id' => $sectors['engineering']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'btech-cse',
                'name_hindi' => 'B.Tech Computer Science Engineering',
                'name_english' => 'B.Tech Computer Science Engineering',
                'description_hindi' => 'कंप्यूटर साइंस इंजीनियरिंग में सॉफ्टवेयर डेवलपमेंट, AI, मशीन लर्निंग, डेटा साइंस और वेब डेवलपमेंट शामिल है।',
                'description_english' => 'Computer Science Engineering includes software development, AI, machine learning, data science, and web development.',
                'duration' => '4 years',
                'eligibility_hindi' => '12वीं PCM (भौतिकी, रसायन, गणित) में कम से कम 60% अंक, JEE मुख्य परीक्षा पास',
                'eligibility_english' => '12th PCM (Physics, Chemistry, Mathematics) with minimum 60% marks, Pass JEE Main',
                'job_prospects_hindi' => 'सॉफ्टवेयर इंजीनियर, डेटा साइंटिस्ट, ऐप डेवलपर, सिस्टम एनालिस्ट',
                'job_prospects_english' => 'Software Engineer, Data Scientist, App Developer, System Analyst',
                'avg_salary_hindi' => '₹3-8 लाख प्रारंभिक, ₹10-25 लाड अनुभवी',
                'avg_salary_english' => '₹3-8 lakhs entry level, ₹10-25 lakhs experienced',
                'required_subjects_hindi' => ['गणित', 'भौतिकी', 'रसायन', 'कंप्यूटर विज्ञान'],
                'required_subjects_english' => ['Mathematics', 'Physics', 'Chemistry', 'Computer Science'],
                'skills_needed_hindi' => ['प्रोग्रामिंग', 'लॉजिकल थिंकिंग', 'समस्या समाधान', 'टीमवर्क'],
                'skills_needed_english' => ['Programming', 'Logical Thinking', 'Problem Solving', 'Teamwork'],
                'course_type' => 'degree',
                'sort_order' => 1,
            ],
            [
                'sector_id' => $sectors['engineering']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'btech-mechanical',
                'name_hindi' => 'B.Tech Mechanical Engineering',
                'name_english' => 'B.Tech Mechanical Engineering',
                'description_hindi' => 'मैकेनिकल इंजीनियरिंग में मशीनों, इंजन, ऑटोमोबाइल और विनिर्माण प्रक्रियाओं का अध्ययन होता है।',
                'description_english' => 'Mechanical Engineering deals with machines, engines, automobiles, and manufacturing processes.',
                'duration' => '4 years',
                'eligibility_hindi' => '12वीं PCM में कम से कम 60% अंक, JEE मुख्य परीक्षा पास',
                'eligibility_english' => '12th PCM with minimum 60% marks, Pass JEE Main',
                'job_prospects_hindi' => 'मैकेनिकल इंजीनियर, ऑटोमोबाइल इंजीनियर, मैन्युफैक्चरिंग इंजीनियर',
                'job_prospects_english' => 'Mechanical Engineer, Automobile Engineer, Manufacturing Engineer',
                'avg_salary_hindi' => '₹3-6 लाख प्रारंभिक, ₹8-18 लाख अनुभवी',
                'avg_salary_english' => '₹3-6 lakhs entry level, ₹8-18 lakhs experienced',
                'required_subjects_hindi' => ['गणित', 'भौतिकी', 'रसायन'],
                'required_subjects_english' => ['Mathematics', 'Physics', 'Chemistry'],
                'skills_needed_hindi' => ['डिज़ाइनिंग', 'एनालिटिकल थिंकिंग', 'प्रैक्टिकल नॉलेज'],
                'skills_needed_english' => ['Designing', 'Analytical Thinking', 'Practical Knowledge'],
                'course_type' => 'degree',
                'sort_order' => 2,
            ],
            
            // Medical Courses
            [
                'sector_id' => $sectors['medicine']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'mbbs',
                'name_hindi' => 'MBBS (Bachelor of Medicine, Bachelor of Surgery)',
                'name_english' => 'MBBS (Bachelor of Medicine, Bachelor of Surgery)',
                'description_hindi' => 'MBBS एक 5.5 साल का कोर्स है जो छात्रों को डॉक्टर बनने के लिए तैयार करता है। इसमें 4.5 साल की अध्ययन और 1 साल का इंटर्नशिप शामिल है।',
                'description_english' => 'MBBS is a 5.5-year course that prepares students to become doctors. It includes 4.5 years of study and 1 year of internship.',
                'duration' => '5.5 years',
                'eligibility_hindi' => '12वीं PCB (भौतिकी, रसायन, जीव विज्ञान) में कम से कम 50% अंक, NEET-UG पास',
                'eligibility_english' => '12th PCB (Physics, Chemistry, Biology) with minimum 50% marks, Pass NEET-UG',
                'job_prospects_hindi' => 'डॉक्टर, सर्जन, मेडिकल रिसर्चर, हॉस्पिटल एडमिनिस्ट्रेटर',
                'job_prospects_english' => 'Doctor, Surgeon, Medical Researcher, Hospital Administrator',
                'avg_salary_hindi' => '₹5-12 लाख प्रारंभिक, ₹15-40 लाख अनुभवी',
                'avg_salary_english' => '₹5-12 lakhs entry level, ₹15-40 lakhs experienced',
                'required_subjects_hindi' => ['भौतिकी', 'रसायन', 'जीव विज्ञान'],
                'required_subjects_english' => ['Physics', 'Chemistry', 'Biology'],
                'skills_needed_hindi' => ['एम्पैथी', 'कम्युनिकेशन स्किल', 'क्रिटिकल थिंकिंग', 'हार्डवर्किंग'],
                'skills_needed_english' => ['Empathy', 'Communication Skills', 'Critical Thinking', 'Hardworking'],
                'course_type' => 'degree',
                'sort_order' => 3,
            ],
            [
                'sector_id' => $sectors['medicine']->id,
                'stream_id' => $streams['science']->id,
                'key' => 'bsc-nursing',
                'name_hindi' => 'B.Sc Nursing',
                'name_english' => 'B.Sc Nursing',
                'description_hindi' => 'नर्सिंग में रोगियों की देखभाल, दवा प्रशासन और स्वास्थ्य शिक्षा शामिल है।',
                'description_english' => 'Nursing involves patient care, medication administration, and health education.',
                'duration' => '4 years',
                'eligibility_hindi' => '12वीं PCB में कम से कम 45% अंक',
                'eligibility_english' => '12th PCB with minimum 45% marks',
                'job_prospects_hindi' => 'रजिस्टर्ड नर्स, नर्स प्रैक्टिशनर, हॉस्पिटल एडमिनिस्ट्रेटर',
                'job_prospects_english' => 'Registered Nurse, Nurse Practitioner, Hospital Administrator',
                'avg_salary_hindi' => '₹2-5 लाख प्रारंभिक, ₹6-12 लाख अनुभवी',
                'avg_salary_english' => '₹2-5 lakhs entry level, ₹6-12 lakhs experienced',
                'required_subjects_hindi' => ['भौतिकी', 'रसायन', 'जीव विज्ञान'],
                'required_subjects_english' => ['Physics', 'Chemistry', 'Biology'],
                'skills_needed_hindi' => ['एम्पैथी', 'पेशेंट केयर', 'कम्युनिकेशन', 'पेसेंस'],
                'skills_needed_english' => ['Empathy', 'Patient Care', 'Communication', 'Patience'],
                'course_type' => 'degree',
                'sort_order' => 4,
            ],

            // Commerce Courses
            [
                'sector_id' => $sectors['commerce']->id,
                'stream_id' => $streams['commerce']->id,
                'key' => 'bcom',
                'name_hindi' => 'B.Com (Bachelor of Commerce)',
                'name_english' => 'B.Com (Bachelor of Commerce)',
                'description_hindi' => 'B.Com में अर्थशास्त्र, लेखा, व्यवसाय अध्ययन और वित्तीय विषय शामिल हैं।',
                'description_english' => 'B.Com includes Economics, Accountancy, Business Studies, and Financial subjects.',
                'duration' => '3 years',
                'eligibility_hindi' => '12वीं किसी भी स्ट्रीम में कम से कम 40% अंक',
                'eligibility_english' => '12th in any stream with minimum 40% marks',
                'job_prospects_hindi' => 'अकाउंटेंट, बैंक क्लर्क, ऑफिस असिस्टेंट, फाइनेंस एनालिस्ट',
                'job_prospects_english' => 'Accountant, Bank Clerk, Office Assistant, Finance Analyst',
                'avg_salary_hindi' => '₹2-4 लाख प्रारंभिक, ₹5-10 लाख अनुभवी',
                'avg_salary_english' => '₹2-4 lakhs entry level, ₹5-10 lakhs experienced',
                'required_subjects_hindi' => ['अर्थशास्त्र', 'लेखा', 'व्यवसाय अध्ययन', 'गणित'],
                'required_subjects_english' => ['Economics', 'Accountancy', 'Business Studies', 'Mathematics'],
                'skills_needed_hindi' => ['नंबर हैंडलिंग', 'अटेंशन टू डिटेल', 'एनालिटिकल स्किल'],
                'skills_needed_english' => ['Number Handling', 'Attention to Detail', 'Analytical Skills'],
                'course_type' => 'degree',
                'sort_order' => 5,
            ],
            [
                'sector_id' => $sectors['commerce']->id,
                'stream_id' => $streams['commerce']->id,
                'key' => 'ca-foundation',
                'name_hindi' => 'CA (Chartered Accountancy)',
                'name_english' => 'CA (Chartered Accountancy)',
                'description_hindi' => 'चार्टर्ड अकाउंटेंसी एक प्रतिष्ठित पेशा है जो लेखांकन, ऑडिट, टैक्स और फाइनेंस में विशेषज्ञता प्रदान करता है।',
                'description_english' => 'Chartered Accountancy is a prestigious profession providing expertise in accounting, audit, tax, and finance.',
                'duration' => '4-5 years',
                'eligibility_hindi' => '12वीं पास (किसी भी स्ट्रीम), CA Foundation परीक्षा पास',
                'eligibility_english' => '12th pass (any stream), Pass CA Foundation exam',
                'job_prospects_hindi' => 'चार्टर्ड अकाउंटेंट, ऑडिटर, टैक्स कंसल्टेंट, फाइनेंस एडवाइजर',
                'job_prospects_english' => 'Chartered Accountant, Auditor, Tax Consultant, Finance Advisor',
                'avg_salary_hindi' => '₹4-8 लाख प्रारंभिक, ₹15-50 लाख अनुभवी',
                'avg_salary_english' => '₹4-8 lakhs entry level, ₹15-50 lakhs experienced',
                'required_subjects_hindi' => ['लेखा', 'अर्थशास्त्र', 'गणित', 'व्यवसाय विधि'],
                'required_subjects_english' => ['Accountancy', 'Economics', 'Mathematics', 'Business Law'],
                'skills_needed_hindi' => ['अनालिटिकल स्किल', 'एथिक्स', 'हार्डवर्क', 'कम्युनिकेशन'],
                'skills_needed_english' => ['Analytical Skills', 'Ethics', 'Hardwork', 'Communication'],
                'course_type' => 'professional',
                'sort_order' => 6,
            ],

            // Arts Courses
            [
                'sector_id' => $sectors['law']->id,
                'stream_id' => $streams['arts']->id,
                'key' => 'llb',
                'name_hindi' => 'LLB (Bachelor of Laws)',
                'name_english' => 'LLB (Bachelor of Laws)',
                'description_hindi' => 'LLB में भारतीय कानून, संविधान, आपराधिक कानून और नागरिक कानून का अध्ययन होता है।',
                'description_english' => 'LLB covers Indian Law, Constitution, Criminal Law, and Civil Law.',
                'duration' => '3 years',
                'eligibility_hindi' => 'किसी भी स्ट्रीम में स्नातक, CLAT या अन्य लॉ एंट्रेंस पास',
                'eligibility_english' => 'Graduation in any stream, Pass CLAT or other law entrance',
                'job_prospects_hindi' => 'वकील, लीगल एडवाइजर, जज, लीगल कंसल्टेंट',
                'job_prospects_english' => 'Lawyer, Legal Advisor, Judge, Legal Consultant',
                'avg_salary_hindi' => '₹3-6 लाख प्रारंभिक, ₹10-30 लाख अनुभवी',
                'avg_salary_english' => '₹3-6 lakhs entry level, ₹10-30 lakhs experienced',
                'required_subjects_hindi' => ['कानून', 'संविधान', 'आपराधिक कानून'],
                'required_subjects_english' => ['Law', 'Constitution', 'Criminal Law'],
                'skills_needed_hindi' => ['अर्ग्यूमेंटेशन', 'रीडिंग स्किल', 'रीसर्च स्किल', 'एथिक्स'],
                'skills_needed_english' => ['Argumentation', 'Reading Skills', 'Research Skills', 'Ethics'],
                'course_type' => 'degree',
                'sort_order' => 7,
            ],

            // Vocational Courses
            [
                'sector_id' => $sectors['skills']->id,
                'stream_id' => $streams['vocational']->id,
                'key' => 'iti-electrician',
                'name_hindi' => 'ITI Electrician',
                'name_english' => 'ITI Electrician',
                'description_hindi' => 'ITI इलेक्ट्रिशियन में विद्युत तारों, सर्किट्स और इलेक्ट्रिकल इंस्टॉलेशन का प्रशिक्षण होता है।',
                'description_english' => 'ITI Electrician provides training in electrical wiring, circuits, and electrical installation.',
                'duration' => '2 years',
                'eligibility_hindi' => '10वीं पास',
                'eligibility_english' => '10th pass',
                'job_prospects_hindi' => 'इलेक्ट्रिशियन, इलेक्ट्रिकल टेक्निशियन, इलेक्ट्रिकल कॉन्ट्रैक्टर',
                'job_prospects_english' => 'Electrician, Electrical Technician, Electrical Contractor',
                'avg_salary_hindi' => '₹1.5-3 लाख प्रारंभिक, ₹4-8 लाख अनुभवी',
                'avg_salary_english' => '₹1.5-3 lakhs entry level, ₹4-8 lakhs experienced',
                'required_subjects_hindi' => ['गणित', 'विज्ञान', 'तकनीकी स्किल'],
                'required_subjects_english' => ['Mathematics', 'Science', 'Technical Skills'],
                'skills_needed_hindi' => ['हैंड्स-ऑन स्किल', 'समस्या समाधान', 'सेफ्टी अवेयरनेस'],
                'skills_needed_english' => ['Hands-on Skills', 'Problem Solving', 'Safety Awareness'],
                'course_type' => 'diploma',
                'sort_order' => 8,
            ],
            [
                'sector_id' => $sectors['skills']->id,
                'stream_id' => $streams['vocational']->id,
                'key' => 'iti-fitter',
                'name_hindi' => 'ITI Fitter',
                'name_english' => 'ITI Fitter',
                'description_hindi' => 'ITI Fitter में मशीन पार्ट्स बनाना, एसेम्बलिंग और मेंटेनेंस का प्रशिक्षण होता है।',
                'description_english' => 'ITI Fitter provides training in making machine parts, assembly, and maintenance.',
                'duration' => '2 years',
                'eligibility_hindi' => '10वीं पास',
                'eligibility_english' => '10th pass',
                'job_prospects_hindi' => 'फिटर, मशीन ऑपरेटर, मैन्युफैक्चरिंग वर्कर',
                'job_prospects_english' => 'Fitter, Machine Operator, Manufacturing Worker',
                'avg_salary_hindi' => '₹1.5-3 लाख प्रारंभिक, ₹4-7 लाख अनुभवी',
                'avg_salary_english' => '₹1.5-3 lakhs entry level, ₹4-7 lakhs experienced',
                'required_subjects_hindi' => ['गणित', 'विज्ञान', 'हैंड्स-ऑन वर्क'],
                'required_subjects_english' => ['Mathematics', 'Science', 'Hands-on Work'],
                'skills_needed_hindi' => ['प्रैक्टिकल स्किल', 'प्रेसिशन वर्क', 'मैनुअल डेक्स्टेरिटी'],
                'skills_needed_english' => ['Practical Skills', 'Precision Work', 'Manual Dexterity'],
                'course_type' => 'diploma',
                'sort_order' => 9,
            ],
        ];

        foreach ($courses as $course) {
            Course::updateOrCreate(
                ['key' => $course['key']],
                $course
            );
        }
    }
}
